# Generated by Django 4.0 on 2022-01-28 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='Hola, soy un post blanco.', max_length=255),
        ),
    ]
